version: '3.2'
services:
  app: &app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: docker/app/start_flask.sh
    env_file: docker/.env.dev
    restart: always
    volumes:
      - ".:/code"
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"

  rabbit:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=talks_tue
    ports:
      - "5672:5672"
      - "15672:15672"

  celery_worker:
    <<: *app
    command: docker/app/start_worker.sh
    ports: []
    depends_on:
      - db
      - rabbit

  celery_beat:
    <<: *app
    command: docker/app/start_beat.sh
    ports: []
    depends_on:
      - db
      - rabbit
