version: '3'
services:
  app: &app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: docker/app/start.sh
    env_file: docker/.env
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:3.2

  celery_worker:
    <<: *app
    command: docker/celery/start_worker.sh
    ports: []
    depends_on:
      - db
      - redis

  celery_beat:
    <<: *app
    command: docker/celery/start_beat.sh
    ports: []
    depends_on:
      - db
      - redis
