version: '3.2'
services:
  app: &app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: docker/app/start_flask.sh
    env_file: .env
    restart: always
    volumes:
      - ".:/code"
    ports:
      - target: 5000
        published: 80
        protocol: tcp
        mode: host
      - target: 5000
        published: 443
        protocol: tcp
        mode: host
    depends_on:
      - db

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    restart: always
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=talks_tue
    expose:
      - "5672"
      - "15672"

  celery_worker:
    <<: *app
    command: docker/app/start_worker.sh
    ports: []
    depends_on:
      - db
      - rabbit

  celery_beat:
    <<: *app
    command: docker/app/start_beat.sh
    ports: []
    depends_on:
      - db
      - rabbit
