"""empty message

Revision ID: 1044b46fc8f3
Revises: c30da3f71941
Create Date: 2019-02-24 22:39:36.320307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1044b46fc8f3'
down_revision = 'c30da3f71941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker', sa.Column('familiy_name_first', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker', 'familiy_name_first')
    # ### end Alembic commands ###
