"""Added HistoryItems

Revision ID: 1eef0f13482e
Revises: 3e6b38c54b4a
Create Date: 2019-02-28 18:27:48.573137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eef0f13482e'
down_revision = '3e6b38c54b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('target_discriminator', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('speaker', sa.Column('viewable', sa.Boolean(), nullable=True))
    op.add_column('talk', sa.Column('viewable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk', 'viewable')
    op.drop_column('speaker', 'viewable')
    op.drop_table('history_item')
    # ### end Alembic commands ###
