"""rename all tag realtions to topic

Revision ID: 28bcb4ac6be2
Revises: 5b4ac2b6b19c
Create Date: 2019-06-26 08:21:47.580239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "28bcb4ac6be2"
down_revision = "5b4ac2b6b19c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("talk_topics", sa.Column("topic_id", sa.Integer(), nullable=False))
    op.drop_constraint("talk_tags_tag_id_fkey", "talk_topics", type_="foreignkey")
    op.create_foreign_key(None, "talk_topics", "topic", ["topic_id"], ["id"])
    op.drop_column("talk_topics", "tag_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "talk_topics",
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "talk_topics", type_="foreignkey")
    op.create_foreign_key(
        "talk_tags_tag_id_fkey", "talk_topics", "topic", ["tag_id"], ["id"]
    )
    op.drop_column("talk_topics", "topic_id")
    # ### end Alembic commands ###
