"""Add user verification flag and code hash

Revision ID: 3392a92c8d34
Revises: 28bcb4ac6be2
Create Date: 2019-08-15 16:05:09.188913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3392a92c8d34'
down_revision = '28bcb4ac6be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('verification_code_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'verification_code_hash')
    # ### end Alembic commands ###
