"""empty message

Revision ID: 3f12781ddb4a
Revises: f144bd570733
Create Date: 2019-06-06 18:52:56.176143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f12781ddb4a"
down_revision = "f144bd570733"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "username", new_column_name="display_name")
    op.create_index(op.f("ix_user_display_name"), "user", ["display_name"], unique=True)
    op.drop_index("ix_user_username", table_name="user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_user_username", "user", ["display_name"], unique=True)
    op.drop_index(op.f("ix_user_display_name"), table_name="user")
    op.alter_column("user", "display_name", new_column_name="username")
    # ### end Alembic commands ###
