"""Added Subscriptions

Revision ID: 8904bd689b70
Revises: 42ecec5bf9e9
Create Date: 2019-04-13 23:07:50.649939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8904bd689b70'
down_revision = '42ecec5bf9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('remind_me', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_subscription_version_end_transaction_id'), 'subscription_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_subscription_version_operation_type'), 'subscription_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_subscription_version_transaction_id'), 'subscription_version', ['transaction_id'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('remind_me', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    op.drop_index(op.f('ix_subscription_version_transaction_id'), table_name='subscription_version')
    op.drop_index(op.f('ix_subscription_version_operation_type'), table_name='subscription_version')
    op.drop_index(op.f('ix_subscription_version_end_transaction_id'), table_name='subscription_version')
    op.drop_table('subscription_version')
    # ### end Alembic commands ###
