"""empty message

Revision ID: c30da3f71941
Revises: 0a1a02807dc8
Create Date: 2019-02-24 20:51:23.575872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30da3f71941'
down_revision = '0a1a02807dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talk', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talk', 'password_hash')
    # ### end Alembic commands ###
