"""added migration model

Revision ID: f144bd570733
Revises: 60ae78d374aa
Create Date: 2019-05-23 16:16:09.998973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f144bd570733"
down_revision = "60ae78d374aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=128)),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("talk_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["talk_id"], ["talk.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("access_token")
    # ### end Alembic commands ###
